# Ignore test linting to avoid conflicting changes to version stability.
exclude: ^tests/resources/
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-added-large-files
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: no-commit-to-branch
      - id: requirements-txt-fixer
      - id: trailing-whitespace
      - id: fix-byte-order-marker
        exclude: docs/CNAME
      - id: fix-encoding-pragma
        args: [--remove]
      - id: mixed-line-ending
        args: [--fix=lf]
  # - repo: https://github.com/pycqa/flake8
  #   rev: 3.7.9
  #   hooks:
  #     - id: flake8
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.10

    # using ruff instead of flake8, as ruff is faster
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.278
    hooks:
      - id: ruff
        exclude: .*\__init__.py
        args: [--fix, --exit-non-zero-on-fix]
